"""
===============================================================================
AUTHOR:      Minh Khanh Luong
DATE:        (2025-11-09)
===============================================================================
DESCRIPTION:
    This script generates comparative plots for tropical cyclone metrics 
    (VMAX, PMIN, or RMW) using four data sources plus a linear 
    regression baseline. It reads precomputed CNN text reports and MERRA2-
    derived reference fields, computes linear model predictions from 
    training/testing data, and produces a two-panel figure showing:

        (a) Boxplots comparing all five series:
            [MERRA2, Linear Regression, CNN, CNN_ALL, Truth]
        (b) Scatter plots of predictions vs truth.

    The output figure filename includes RMSE and MAE values for each model.

REQUIREMENTS

The script requires text output files for VMAX, PMIN, and RMW metrics, as well as their corresponding ALL configuration reports.
→ Plotting will only proceed once all required reports are available.

It also depends on temporary files generated by TC-net_Universal_data_reader.py.
→ Before running, disable temporary-file deletion by commenting out the cleanup command at the end of the batch job script.
→ Set a fixed (non-random) temp_id value to ensure consistent data access for linear regression.

The batch job script must be executed from the current working directory, since reference files for MERRA-2–based metrics (VMAX, PMIN, RMW) are produced locally. Running from another directory will prevent these reference files from being found.

INPUT FILES:
    • ref_x (.npy/.npz)     : Reference 4D array (N, 5, lon, lat) 
                              → channels: [u_sfc, v_sfc, slp, lat, lon]
    • train_x / train_y     : Training data (N, 13, H, W) and (N, 3)
    • test_x / test_y       : Testing data (M, 13, H, W) and (M, 3)
    • text_report/*.txt     : CNN output files (pred,true per line) for each metric:
                                - VMAX_CNN_RAND.txt / VMAX_ALL_RAND.txt
                                - PMIN_CNN_RAND.txt / PMIN_ALL_RAND.txt
                                - RMW_CNN_RAND.txt  / RMW_ALL_RAND.txt

OUTPUTS:
    • A PNG figure saved in "reports/" with RMSE and MAE encoded in the filename.
      Example: fig_RMW_rand_rmse1.23_1.56_1.78_mae0.89_1.02_1.11.png

METRIC UNITS:
    • VMAX → knots (kt)
    • PMIN → millibar / hPa (mb)
    • RMW  → nautical miles (nm)

NOTES:
    - The MERRA2-based reference statistics (VMAX, PMIN, RMW) are derived using
      a 6°×5° window centered on the storm and converted to the units above.
    - The script uses NumPy and TensorFlow for metrics, and matplotlib for plotting.
===============================================================================
"""

import os
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import argparse

def parse_args():
    p = argparse.ArgumentParser(description="Construct TCNN paths from raw components.")

    # ==== Defaults from your batch job ====
    p.add_argument("--workdir",       type=str, default="/N/slate/kmluong/TC-net-cnn_workdir",
                   help="Base working dir")
    p.add_argument("--data_source",   type=str, default="MERRA2",
                   help="Data source label")
    p.add_argument("--exp_name",      type=str, default="000",
                   help="Experiment code (e.g., 000)")
    p.add_argument("--windowsize_x",  type=int, default=18,
                   help="Window size (x-direction)")
    p.add_argument("--var_num",       type=int, default=13,
                   help="Number of variables")
    p.add_argument("--temp_id",       type=str, default="sssssdd",
                   help="Fixed temp id suffix for npy files")
    p.add_argument("--result_folder",          type=str, default="YEAR",
                   help="Folder name to save figs under text_report")
    p.add_argument("--i",             type=int, default=5,
                   help="Starting index, as there are 4 models")
    p.add_argument("--name", type=str, default="FIG",
                   help="Short tag to include in the output figure filename")
    p.add_argument("--unit", type=str, default=None,
                   help="Override unit label (otherwise auto based on metric)")

    return p.parse_args()


def build_paths(a):
    import os

    # ---- Derived bases ----
    base_dir   = os.path.join(a.workdir, f"{a.data_source}_{a.exp_name}{a.windowsize_x}w")
    report_dir = os.path.join(base_dir, "text_report", a.result_folder)

    # ---- Temp arrays written by the data reader ----
    ref_x   = os.path.join(report_dir, f"ref_x_{a.temp_id}.npy")
    train_x = os.path.join(report_dir, f"train_x_{a.temp_id}.npy")
    train_y = os.path.join(report_dir, f"train_y_{a.temp_id}.npy")
    test_x  = os.path.join(report_dir, f"test_x_{a.temp_id}.npy")
    test_y  = os.path.join(report_dir, f"test_y_{a.temp_id}.npy")

    # ---- Indices per metric ----
    idx_vmax = a.i
    idx_pmin = a.i + 1
    idx_rmw  = a.i + 2
    idx_all  = a.i + 3

    # ---- Model name cores (encode window + var count) ----
    model_core_vmax = f"TCNN{idx_vmax}_{a.windowsize_x}w_{a.var_num}c"
    model_core_pmin = f"TCNN{idx_pmin}_{a.windowsize_x}w_{a.var_num}c"
    model_core_rmw  = f"TCNN{idx_rmw}_{a.windowsize_x}w_{a.var_num}c"
    model_core_all  = f"TCNN{idx_all}_{a.windowsize_x}w_{a.var_num}c"

    # ---- Text reports (single-metric runs) ----
    vm = os.path.join(report_dir, f"VMAX{model_core_vmax}_{a.data_source}_VMAX.txt")
    pm = os.path.join(report_dir, f"PMIN{model_core_pmin}_{a.data_source}_PMIN.txt")
    rm = os.path.join(report_dir, f"RMW{model_core_rmw}_{a.data_source}_RMW.txt")

    # ---- Text reports (ALL-config run; one file per metric, model ends with _ALL) ----
    vma = os.path.join(report_dir, f"VMAX{model_core_all}_{a.data_source}_ALL.txt")
    pma = os.path.join(report_dir, f"PMIN{model_core_all}_{a.data_source}_ALL.txt")
    rma = os.path.join(report_dir, f"RMW{model_core_all}_{a.data_source}_ALL.txt")

    return {
        "BASE_DIR": base_dir,
        "REPORT_DIR": report_dir,

        # Temp arrays
        "ref_x": ref_x,
        "train_x": train_x,
        "train_y": train_y,
        "test_x": test_x,
        "test_y": test_y,

        # Model cores per metric
        "MODEL_CORE_VMAX": model_core_vmax,
        "MODEL_CORE_PMIN": model_core_pmin,
        "MODEL_CORE_RMW": model_core_rmw,
        "MODEL_CORE_ALL": model_core_all,

        # Text reports
        "vm": vm,
        "pm": pm,
        "rm": rm,
        "vma": vma,
        "pma": pma,
        "rma": rma,
    }

# =================== Metrics ===================
def root_mean_squared_error(y_true, y_pred):
    m = tf.keras.metrics.RootMeanSquaredError()
    m.update_state(y_true, y_pred)
    return m.result().numpy()

def MAE(y_true, y_pred):
    m = tf.keras.metrics.MeanAbsoluteError()
    m.update_state(y_true, y_pred)
    return m.result().numpy()

# =================== Plotting ===================
def plot_five_with_linear(arrays, labels, name, unit, y_pred, report_directory=None):
    """
    arrays: list/tuple of 4 arrays [A, B, C, D]
      A: MERRA-derived target (from ref_x stats)
      B: CNN (single) prediction series
      C: CNN_ALL prediction series
      D: Truth series
    labels: list/tuple of 4 labels matching A,B,C,D
    y_pred: 1D numpy array (linear regression predictions) to insert as the 2nd box
    """
    if len(arrays) != 4 or len(labels) != 4:
        raise ValueError("Provide exactly four base arrays and four labels (A,B,C,D).")

    # Unpack and ensure numpy
    A, B, C, D = (np.asarray(x) for x in arrays)
    y_pred = np.asarray(y_pred)

    # Build 5-series order: [A, y_pred, B, C, D]
    series = [A, y_pred, B, C, D]
    lab5   = [labels[0], "Linear\nRegression", labels[1], labels[2], labels[3]]

    # Global mask (kept as in your original; if you want per-series NaN masking, we can switch)
    mask = np.ones_like(series[0], dtype=bool)
    for s in series:
        if s.shape != series[0].shape:
            raise ValueError("All arrays must be the same length along the sample axis.")
        mask &= (s != -1)
    series = [s[mask] for s in series]
    A, YLIN, B, C, D = series

    # Metrics for all three predictors vs truth
    rmse_lin = root_mean_squared_error(D, YLIN)
    mae_lin  = MAE(D, YLIN)
    rmse1    = root_mean_squared_error(D, B)
    mae1     = MAE(D, B)
    rmse2    = root_mean_squared_error(D, C)
    mae2     = MAE(D, C)

    colors = ['g', 'y', 'b', 'r', 'k']
    fig, axs = plt.subplots(1, 2, figsize=(14, 6),
                            gridspec_kw={'width_ratios': [1.2, 1]})

    # (a) boxplots
    bps = axs[0].boxplot([A, YLIN, B, C, D], patch_artist=True)
    for patch, color in zip(bps['boxes'], colors):
        patch.set_facecolor(color)
    axs[0].set_xticklabels(lab5, fontsize=14, rotation=0)
    axs[0].set_ylabel(unit, fontsize=16)
    axs[0].grid(True)
    axs[0].text(0.95, 0.05, '(a)', transform=axs[0].transAxes,
                fontsize=16, va='bottom', ha='right',
                bbox=dict(facecolor='white', alpha=0.8, edgecolor='none'))

    # (b) scatter: B, C, YLIN vs D
    for arr, lbl, col in zip([B, C, YLIN],
                             [lab5[2], lab5[3], "Linear Regression"],
                             [colors[2], colors[3], colors[1]]):
        axs[1].scatter(D, arr, c=col, label=lbl, alpha=0.7, edgecolors='none')

    mn, mx = D.min(), D.max()
    axs[1].plot([mn, mx], [mn, mx], 'r-', alpha=0.5)
    axs[1].set_xlabel(f"{lab5[4]}", fontsize=16)  # truth label
    axs[1].set_ylabel("Prediction", fontsize=16)
    axs[1].grid(True)
    axs[1].legend(fontsize=12, loc='upper left')
    axs[1].text(0.95, 0.05, '(b)', transform=axs[1].transAxes,
                fontsize=16, va='bottom', ha='right',
                bbox=dict(facecolor='white', alpha=0.8, edgecolor='none'))
    axs[1].tick_params(labelsize=12)

    fig.tight_layout(rect=[0, 0, 1, 0.96])

    # Save with metrics in filename
    if report_directory is not None:
        os.makedirs(report_directory, exist_ok=True)
        def fmt(x): return f"{x:.3f}"
        fname = os.path.join(
            report_directory,
            f"fig_{name}_rmse{fmt(rmse_lin)}_{fmt(rmse1)}_{fmt(rmse2)}"
            f"_mae{fmt(mae_lin)}_{fmt(mae1)}_{fmt(mae2)}.png"
        )
        plt.savefig(fname, dpi=300)
        print(f"Saved figure to: {fname}")
    else:
        plt.show()

# =================== Parsing helpers & data prep ===================
def extract_predictions(filename):
    """Read lines after 'Predictions vs Actual Values:' as 'pred,true' floats."""
    pred, true = [], []
    in_data_block = False
    with open(filename, 'r') as f:
        for line in f:
            line = line.strip()
            if line.startswith("Predictions vs Actual Values:"):
                in_data_block = True
                continue
            if in_data_block:
                if not line:
                    break
                try:
                    pval, tval = map(float, line.split(','))
                    pred.append(pval)
                    true.append(tval)
                except ValueError:
                    continue
    return np.array(pred), np.array(true)

def haversine(lat1, lon1, lat2, lon2, radius_km=6371.0):
    """Great-circle distance in km (inputs in degrees)."""
    φ1, φ2 = np.radians(lat1), np.radians(lat2)
    Δφ     = φ2 - φ1
    Δλ     = np.radians(lon2 - lon1)
    a      = np.sin(Δφ/2)**2 + np.cos(φ1)*np.cos(φ2)*np.sin(Δλ/2)**2
    d_km   = 2 * radius_km * np.arcsin(np.sqrt(a))
    return d_km  # km

def _load_array(path: str) -> np.ndarray:
    """Load .npy or .npz (single-array) file."""
    if path.endswith(".npy"):
        return np.load(path)
    if path.endswith(".npz"):
        with np.load(path) as z:
            if len(z.files) != 1:
                raise ValueError(f"{path} contains multiple arrays; please provide a single-array .npz.")
            return z[z.files[0]]
    raise ValueError(f"Unsupported file type for {path}; expected .npy or .npz")

def train_and_eval_linear_models(x_train_path, y_train_path, x_test_path, y_test_path):
    """
    Average X over last two dims -> (N, 13); add bias; solve least squares to 3 targets.
    Returns y_pred_test, y_true_test with shape (M, 3).
    """
    X_tr = _load_array(x_train_path)
    Y_tr = _load_array(y_train_path)
    X_te = _load_array(x_test_path)
    Y_te = _load_array(y_test_path)

    if X_tr.ndim != 4 or X_te.ndim != 4:
        raise ValueError("X_train and X_test must be 4D arrays like (N, 13, H, W).")
    if Y_tr.ndim != 2 or Y_te.ndim != 2:
        raise ValueError("Y_train and Y_test must be 2D arrays like (N, 3).")
    if X_tr.shape[1] != 13 or X_te.shape[1] != 13:
        raise ValueError("Expected 13 channels in X.")
    if Y_tr.shape[1] != 3 or Y_te.shape[1] != 3:
        raise ValueError("Targets must have 3 columns.")

    Xtr_red = X_tr.mean(axis=(-2, -1))
    Xte_red = X_te.mean(axis=(-2, -1))
    N, M = Xtr_red.shape[0], Xte_red.shape[0]
    Xtr_aug = np.concatenate([np.ones((N,1), dtype=Xtr_red.dtype), Xtr_red], axis=1)
    Xte_aug = np.concatenate([np.ones((M,1), dtype=Xte_red.dtype), Xte_red], axis=1)
    B, *_ = np.linalg.lstsq(Xtr_aug, Y_tr, rcond=None)
    Y_pred_te = Xte_aug @ B
    return Y_pred_te, Y_te

# =================== CLI ===================
def _prep_metric_series(metric, paths, stats, y_pred_lin, unit_override=None):
    """
    Returns (A, B, C, D, y_pred_col, label_name, unit) for the given metric.
      A: MERRA2-derived stat
      B: CNN (single)
      C: CNN_ALL
      D: Truth (from the same CNN report)
      y_pred_col: linear baseline column aligned with metric
    """
    metric = metric.lower()
    if metric == "vmax":
        idx = 0
        vm, vma = paths["vm"], paths["vma"]
        if not (os.path.isfile(vm) and os.path.isfile(vma)):
            raise FileNotFoundError(f"Missing VMAX reports:\n  {vm}\n  {vma}")
        B_pred, B_true = extract_predictions(vm)
        C_pred         = extract_predictions(vma)[0]
        label_name = "VMAX"
        unit = unit_override or "knots"
    elif metric == "pmin":
        idx = 1
        pm, pma = paths["pm"], paths["pma"]
        if not (os.path.isfile(pm) and os.path.isfile(pma)):
            raise FileNotFoundError(f"Missing PMIN reports:\n  {pm}\n  {pma}")
        B_pred, B_true = extract_predictions(pm)
        C_pred         = extract_predictions(pma)[0]
        label_name = "PMIN"
        unit = unit_override or "mb"
    elif metric == "rmw":
        idx = 2
        rm, rma = paths["rm"], paths["rma"]
        if not (os.path.isfile(rm) and os.path.isfile(rma)):
            raise FileNotFoundError(f"Missing RMW reports:\n  {rm}\n  {rma}")
        B_pred, B_true = extract_predictions(rm)
        C_pred         = extract_predictions(rma)[0]
        label_name = "RMW"
        unit = unit_override or "nm"
    else:
        raise ValueError("metric must be one of: vmax, pmin, rmw")

    A = stats[:, idx]
    B = B_pred
    C = C_pred
    D = B_true
    y_pred_col = y_pred_lin[:, idx]

    # Align lengths defensively
    L = min(len(A), len(B), len(C), len(D), len(y_pred_col))
    return A[:L], B[:L], C[:L], D[:L], y_pred_col[:L], label_name, unit

def extract_wind_slp_stats(ref_x):
    """
    ref_x: np.ndarray, shape (N,5,lon,lat)
      channel 0 = u_sfc
      channel 1 = v_sfc
      channel 2 = slp
      channel 3 = latitudes (deg), same shape (lon,lat)
      channel 4 = longitudes (deg), same shape (lon,lat)
    Returns: np.ndarray shape (N,3) of [max_wind, min_slp, distance_nm]
    """
    N, _, nlon, nlat = ref_x.shape
    # pixel radii: exactly ±3° in each direction
    lon_res = 0.5
    lat_res = 0.625
    i_radius = int(np.ceil(3.0 / lon_res))    # 3°/0.5° → 6 pixels east/west
    j_radius = int(np.ceil(3.0 / lat_res))    # 3°/0.625° → 4 pixels north/south

    # Pre‑extract static lat/lon grids (identical for every sample)
    lat_grid = ref_x[0,3]   # shape (nlon,nlat)
    lon_grid = ref_x[0,4]

    out = np.zeros((N,3), dtype=float)  # [max_wind, min_slp, dist_nm]

    for idx in range(N):
        u   = ref_x[idx,0]
        v   = ref_x[idx,1]
        slp = ref_x[idx,2]

        # 1) wind speed magnitude
        wind = np.sqrt(u*u + v*v)
        # — if the whole wind field is NaN, set everything to 1
        if np.all(np.isnan(wind)):
            out[idx] = [-1, -1, -1]
            continue
        # 2) max‐wind location
        flat_idx = np.nanargmax(wind)
        i0, j0  = np.unravel_index(flat_idx, wind.shape)
        max_w   = wind[i0,j0]

     # define a (2*i_radius+1)×(2*j_radius+1) window centered on (i0,j0)
        i1 = max(0,               i0 - i_radius)
        i2 = min(nlon, i0 + i_radius + 1)  # +1 to include the upper bound
        j1 = max(0,               j0 - j_radius)
        j2 = min(nlat, j0 + j_radius + 1)

        sub_slp = slp[i1:i2, j1:j2]
        # 4) find min‐SLP in that window
        sub_flat = np.nanargmin(sub_slp)
        di, dj   = np.unravel_index(sub_flat, sub_slp.shape)
        i_min    = i1 + di
        j_min    = j1 + dj
        min_p    = slp[i_min,j_min]

        # 5) compute great‐circle distance
        lat0, lon0 = lat_grid[i0,j0], lon_grid[i0,j0]
        latm, lonm = lat_grid[i_min,j_min], lon_grid[i_min,j_min]
        dist_km    = haversine(lat0, lon0, latm, lonm)
        # convert speed m/s → knots, and pressure Pa → mb
        max_w_kt   = max_w   * 1.94384
        min_p_bar  = min_p   / 1e2
        
        out[idx] = [max_w_kt, min_p_bar, dist_km*0.539957]

    return out



def main():
    args = parse_args()

    # Build paths & decide output directory
    paths = build_paths(args)
    report_dir = paths["REPORT_DIR"]  # we’ll keep figures grouped by YEAR / derived folder
    os.makedirs(report_dir, exist_ok=True)

    # Resolve data array paths (no CLI overrides in this minimal patch; add if you need)
    ref_x   = paths["ref_x"]
    train_x = paths["train_x"]
    train_y = paths["train_y"]
    test_x  = paths["test_x"]
    test_y  = paths["test_y"]

    # 1) Load ref stats once
    ref   = _load_array(ref_x)
    stats = extract_wind_slp_stats(ref)

    # 2) Train/compute linear baseline once
    y_pred_lin, y_true_lin = train_and_eval_linear_models(train_x, train_y, test_x, test_y)

    # 3) Make all three figures in one go
    for metric in ["vmax", "pmin", "rmw"]:
        A, B, C, D, ylin, label_name, unit = _prep_metric_series(
            metric, paths, stats, y_pred_lin, unit_override=None
        )
        plot_five_with_linear(
            arrays=[A, B, C, D],
            labels=["MERRA2", "CNN", "CNN_ALL", "Truth"],
            name=f"{label_name}_{args.name}",
            unit=unit,
            y_pred=ylin,
            report_directory=report_dir
        )

if __name__ == "__main__":
    main()
